cat << EOF > ./agent-config.yaml
metrics:
  global:
    scrape_interval: 60s
  configs:
  - name: hosted-prometheus
    scrape_configs:
      - job_name: node
        static_configs:
        - targets: ['localhost:9100']
    remote_write:
      - url: https://prometheus-prod-26-prod-ap-south-0.grafana.net/api/prom/push
        basic_auth:
          username: 925971
          password: glc_eyJvIjoiODI4NjQ5IiwibiI6ImRiX2dyYWZhbmFfdG9rZW4iLCJrIjoiOGk5aG5BMzY1czhuNXAyQlBCYjJiOGVtIiwibSI6eyJyIjoicHJvZC1hcC1zb3V0aC0wIn19
EOF